### ISSUE TITLE
Specify default versions for shared workflows

### ISSUE THREAD

**Issue by marns93** [pulumiverse/infra#47]
In https://github.com/pulumiverse/infra/commit/ba261001a254653bd8a218dc8dc82d14526d3a4d there was a change to make the language versions configurable, which is very nice.

But this breaks the pipeline in https://github.com/pulumiverse/pulumi-heroku/actions/runs/3497205846, because the versions are not specified and they are required. 

So my questions is:
Should we define default values in cases they are not specified?

@ringods

**Comment by ringods** [comment]
@marns93 as indicated in the PR, please refrain from using `latest on main` for consuming these reusable workflows. You can use tag `actions-workflows-v0.0.1` to lock your provider to a working version of the reusable workflows.

**Comment by marns93** [comment]
> @marns93 as indicated in the PR, please refrain from using `latest on main` for consuming these reusable workflows. You can use tag `actions-workflows-v0.0.1` to lock your provider to a working version of the reusable workflows.

Okay I see. This makes totally sense. I will update the provider and use tags.
